export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_RATING = 'ADD_RATING';
export const WORKERS_LOADING = 'WORKERS_LOADING';
export const WORKERS_FAILED = 'WORKERS_FAILED';
export const ADD_WORKERS = 'ADD_WORKERS';

export const CLIENTS_LOADING = 'CLIENTS_LOADING';
export const CLIENTS_FAILED = 'CLIENTS_FAILED';
export const ADD_CLIENTS = 'ADD_CLIENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const RATINGS_FAILED = 'RATINGS_FAILED';
export const ADD_RATINGS = 'ADD_RATINGS';